version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_LOG_LEVEL=trace
      - CLICKHOUSE_ENABLE_PLAY_UI=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  clickhouse-ui:
    image: spoonest/clickhouse-tabix-web-client
    container_name: clickhouse-ui
    ports:
      - "8080:80"
    environment:
      - CH_HOST=clickhouse
      - CH_PORT=8123
      - CH_USER=default
      - CH_PASSWORD=clickhouse
      - CH_DB=default
    depends_on:
      - clickhouse
    restart: unless-stopped

volumes:
  clickhouse-data: 